from __future__ import annotations

from app.core.keyword_rules import (
    DISCOUNT_KEYWORDS,
    DISCOUNT_PERCENT_PATTERN,
    GROUPING_IGNORE_TOKENS,
    MEDIUM_NEGATIVE_KEYWORDS,
    MEDIUM_POSITIVE_KEYWORDS,
    PLATFORM_MEGA_SALES,
    STRONG_NEGATIVE_KEYWORDS,
    STRONG_POSITIVE_KEYWORDS,
    WIDE_SCOPE_KEYWORDS,
)

__all__ = [
    "DISCOUNT_KEYWORDS",
    "DISCOUNT_PERCENT_PATTERN",
    "GROUPING_IGNORE_TOKENS",
    "MEDIUM_NEGATIVE_KEYWORDS",
    "MEDIUM_POSITIVE_KEYWORDS",
    "PLATFORM_MEGA_SALES",
    "STRONG_NEGATIVE_KEYWORDS",
    "STRONG_POSITIVE_KEYWORDS",
    "WIDE_SCOPE_KEYWORDS",
]
